
[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot==20.7",
    "reportlab>=4.3.0",
    "telegram>=0.0.1",
    "trafilatura>=2.0.0",
]
